### ISSUE TITLE
[Bug]: Invalid Player Data Lockout on 1.20.1

### ISSUE THREAD

**Issue by Paulie820** [TheosCreation/CreateCompression#4]
### Minecraft Version

1.18

### Mod Version

1.20.1-1.6.0

### Is Compressium Loaded

Not Loaded

### What happened?

When loading Create Compression 1.6.0 with Quark 4.0-433, new and old worlds will load and immediately kick the player yielding an 'invalid player data' error message. According to Quark devs recipe implementation may be causing the fault. Log attached, see line 3039. 

Link to issue from Quark end:
https://github.com/VazkiiMods/Quark/issues/4635#issue-2116755284

### latest.log

<script src="https://gist.github.com/Paulie820/6ede156199574c4623b1196e598c322a.js"></script>

**Comment by TheosCreation** [comment]
Should be fixed in later versions. I think it was recipes that had errors in them and they were irrelevant to this mod
