### ISSUE TITLE
[Bug]: Not able to Compress grass Block

### ISSUE THREAD

**Issue by VillainVibe** [TheosCreation/CreateCompression#5]
### Minecraft Version

1.18

### Mod Version

1.8.0

### Is Compressium Loaded

Loaded

### What happened?

Im using Minecraft 1.20.1 but can't select it here! 
I'm not able to compress grass blocks into there compressed form ...

![image](https://github.com/TheosCreation/CreateCompression/assets/161154905/fb0cd6c5-5f2b-4f33-a66f-d24e4619c605)

Instead you're able to compress grass instead ... Why ?

![image](https://github.com/TheosCreation/CreateCompression/assets/161154905/610f5fa7-a661-4756-bac8-8caef058c8c2)

### latest.log

No log

**Comment by TheosCreation** [comment]
omg thats so bad of me its really common to miss one word, so instead of minecraft:grass i should have put minecraft:grass_block

**Comment by VillainVibe** [comment]
All good.
Atleast it's a easy fix 😄
