### ISSUE TITLE
[Bug]: Compressed Raw Iron, Copper, and Gold Recipes are Broken - Minecraft Version 1.20.1 - Mod Version 1.8.0

### ISSUE THREAD

**Issue by M0nkeyPr0grammer** [TheosCreation/CreateCompression#6]
### Minecraft Version

1.18

### Mod Version

CreateCompression-1.20.1-1.8.0

### Is Compressium Loaded

Not Loaded

### What happened?

According to KubeJS Server Logs, I get these errors: 
[server.log](https://github.com/TheosCreation/CreateCompression/files/15210416/server.log)

Looks like something went wrong when you created these new items breaking all their recipes. I was going to attempt to fix the issues via KubeJS so that they work within my Modpack, but I can't seem to see anything wrong with your recipe creation.

### latest.log

https://gist.github.com/M0nkeyPr0grammer/f46770d57195589b7aeb84005bbe3570

**Comment by TheosCreation** [comment]
Thank you found the issue the blocks werent in the registry so they didnt even exist in the game at all so the recipes wouldnt work. Blocks have been added successfully

**Comment by M0nkeyPr0grammer** [comment]
Ah, that makes total sense. Thanks for the quick fix!
