### ISSUE TITLE
[Bug]:  Please fix decompressing compressed grass to grass block.

### ISSUE THREAD

**Issue by VillainVibe** [TheosCreation/CreateCompression#7]
### Minecraft Version

1.18

### Mod Version

1.20.1  - 1.8.1

### Is Compressium Loaded

Loaded

### What happened?

Version 1.20.1 
You fixed the compressing issue but  not the decompressing issue. 
You get grass back from you're blocks.

![image](https://github.com/TheosCreation/CreateCompression/assets/161154905/e62de292-9193-4ce8-ab4f-d1bd684df25c)

Cheers

### latest.log

No log

**Comment by TheosCreation** [comment]
fixed in 1.8.2

**Comment by VillainVibe** [comment]
Did you upload to modrinth to ? 
I don't see 1.8.2 there only on curseforge

**Comment by VillainVibe** [comment]
I downloaded 1.8.2 from curseforge 
Decompressing Grass blocks still give grass as output 
![image](https://github.com/TheosCreation/CreateCompression/assets/161154905/6205b4b7-2ce0-444a-add8-ddaece5d5667)
